# Generated by Django 6.0 on 2025-12-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude_start', models.FloatField(verbose_name='Longitude de Início')),
                ('latitude_start', models.FloatField(verbose_name='Latitude de Início')),
                ('longitude_end', models.FloatField(verbose_name='Longitude de Fim')),
                ('latitude_end', models.FloatField(verbose_name='Latitude de Fim')),
                ('length', models.FloatField(verbose_name='Comprimento (metros)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segmento de Estrada',
                'verbose_name_plural': 'Segmentos de Estrada',
                'db_table': 'road_segments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpeedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_speed', models.FloatField(verbose_name='Velocidade Média (km/h)')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora da Leitura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='traffic_monitor.roadsegment', verbose_name='Segmento de Estrada')),
            ],
            options={
                'verbose_name': 'Leitura de Velocidade',
                'verbose_name_plural': 'Leituras de Velocidade',
                'db_table': 'speed_readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
